install:
  - yarn install
env:
  - CI="true"

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
- yarn testrpc &
- sleep 1

script:
- yarn compile
- yarn migrate-testrpc
- yarn ci
