toc:
  - Polymath
  - name: Contracts
  - ContractWrapper
  - PolyToken
  - name: Types
  - Web3Provider
  - Web3Filter
  - IndexedFilterValues
  - EventCallback
  - BlockRange
  - Log
  - TransferEventArgs
  - AllowanceEventArgs
  - PolyTokenEventArgs
